name: Build and Deploy to GKE

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/573325332123/locations/global/workloadIdentityPools/github-actions-cicd/providers/github'
        service_account: 'geolocview-serviceaccount@third-nature-400716.iam.gserviceaccount.com'

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker

    - name: Build Backend Container
      run: |
        docker build -t gcr.io/third-nature-400716/backend:$GITHUB_SHA ./backend
        docker push gcr.io/third-nature-400716/backend:$GITHUB_SHA

    - name: Build Frontend Container
      run: |
        docker build -t gcr.io/third-nature-400716/frontend:$GITHUB_SHA ./frontend/geolocview
        docker push gcr.io/third-nature-400716/frontend:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/backend-deployment backend=gcr.io/third-nature-400716/backend:$GITHUB_SHA
        kubectl set image deployment/frontend-deployment frontend=gcr.io/third-nature-400716/frontend:$GITHUB_SHA
